default_platform(:android)
platform :android do
  
  # Our lane starts here
  desc "Deploy a new version to the internal testers"
  lane :internal do
    
    begin
      supply(
        track: 'internal',
        apk: '../build/app/outputs/apk/release/app-release.apk',
        json_key: 'app/serviceAccount.json',
      )
    end
  end
  # .. and ends here
end